from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")
        App.resize(719, 309)
        self.centralwidget = QtWidgets.QWidget(App)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 30, 319, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAcceptDrops(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.expX1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expX1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expX1.setMaximum(99999.99)
        self.expX1.setObjectName("expX1")
        self.gridLayout.addWidget(self.expX1, 1, 1, 1, 1)
        self.expX2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expX2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expX2.setMaximum(99999.99)
        self.expX2.setObjectName("expX2")
        self.gridLayout.addWidget(self.expX2, 1, 2, 1, 1)
        self.expX3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expX3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expX3.setMaximum(99999.99)
        self.expX3.setObjectName("expX3")
        self.gridLayout.addWidget(self.expX3, 1, 3, 1, 1)
        self.expX4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expX4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expX4.setMaximum(99999.99)
        self.expX4.setObjectName("expX4")
        self.gridLayout.addWidget(self.expX4, 1, 4, 1, 1)
        self.expX5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expX5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expX5.setMaximum(99999.99)
        self.expX5.setObjectName("expX5")
        self.gridLayout.addWidget(self.expX5, 1, 5, 1, 1)
        self.expY1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expY1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expY1.setMaximum(99999.99)
        self.expY1.setObjectName("expY1")
        self.gridLayout.addWidget(self.expY1, 2, 1, 1, 1)
        self.expY2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expY2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expY2.setMaximum(99999.99)
        self.expY2.setObjectName("expY2")
        self.gridLayout.addWidget(self.expY2, 2, 2, 1, 1)
        self.expY3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expY3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expY3.setMaximum(99999.99)
        self.expY3.setObjectName("expY3")
        self.gridLayout.addWidget(self.expY3, 2, 3, 1, 1)
        self.expY4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expY4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expY4.setMaximum(99999.99)
        self.expY4.setObjectName("expY4")
        self.gridLayout.addWidget(self.expY4, 2, 4, 1, 1)
        self.expY5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expY5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expY5.setMaximum(99999.99)
        self.expY5.setObjectName("expY5")
        self.gridLayout.addWidget(self.expY5, 2, 5, 1, 1)
        self.expZ1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expZ1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expZ1.setMaximum(99999.99)
        self.expZ1.setObjectName("expZ1")
        self.gridLayout.addWidget(self.expZ1, 3, 1, 1, 1)
        self.expZ2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expZ2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expZ2.setMaximum(99999.99)
        self.expZ2.setObjectName("expZ2")
        self.gridLayout.addWidget(self.expZ2, 3, 2, 1, 1)
        self.expZ3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expZ3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expZ3.setMaximum(99999.99)
        self.expZ3.setObjectName("expZ3")
        self.gridLayout.addWidget(self.expZ3, 3, 3, 1, 1)
        self.expZ4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expZ4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expZ4.setMaximum(99999.99)
        self.expZ4.setObjectName("expZ4")
        self.gridLayout.addWidget(self.expZ4, 3, 4, 1, 1)
        self.expZ5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.expZ5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.expZ5.setMaximum(99999.99)
        self.expZ5.setObjectName("expZ5")
        self.gridLayout.addWidget(self.expZ5, 3, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 72, 16))
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 54, 31))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 191, 16))
        self.label_12.setObjectName("label_12")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 191, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.minX = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.minX.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.minX.setMaximum(99999)
        self.minX.setObjectName("minX")
        self.gridLayout_2.addWidget(self.minX, 1, 0, 1, 1)
        self.minY = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.minY.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.minY.setMaximum(99999)
        self.minY.setObjectName("minY")
        self.gridLayout_2.addWidget(self.minY, 1, 1, 1, 1)
        self.minZ = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.minZ.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.minZ.setMaximum(99999)
        self.minZ.setObjectName("minZ")
        self.gridLayout_2.addWidget(self.minZ, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 230, 271, 16))
        self.label_16.setObjectName("label_16")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 250, 301, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.max1 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.max1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max1.setMaximum(999999)
        self.max1.setObjectName("max1")
        self.gridLayout_3.addWidget(self.max1, 1, 0, 1, 1)
        self.max2 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.max2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max2.setMaximum(999999)
        self.max2.setObjectName("max2")
        self.gridLayout_3.addWidget(self.max2, 1, 1, 1, 1)
        self.max3 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.max3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max3.setMaximum(999999)
        self.max3.setObjectName("max3")
        self.gridLayout_3.addWidget(self.max3, 1, 2, 1, 1)
        self.max4 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.max4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max4.setMaximum(999999)
        self.max4.setObjectName("max4")
        self.gridLayout_3.addWidget(self.max4, 1, 3, 1, 1)
        self.max5 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.max5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max5.setMaximum(999999)
        self.max5.setObjectName("max5")
        self.gridLayout_3.addWidget(self.max5, 1, 4, 1, 1)
        self.calcBtn = QtWidgets.QPushButton(self.centralwidget)
        self.calcBtn.setGeometry(QtCore.QRect(500, 280, 71, 24))
        self.calcBtn.setObjectName("calcBtn")
        self.fromExcel = QtWidgets.QPushButton(self.centralwidget)
        self.fromExcel.setGeometry(QtCore.QRect(580, 280, 131, 24))
        self.fromExcel.setObjectName("fromExcel")
        self.inExcel = QtWidgets.QPushButton(self.centralwidget)
        self.inExcel.setGeometry(QtCore.QRect(580, 250, 131, 24))
        self.inExcel.setObjectName("inExcel")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(410, 180, 91, 16))
        self.label_22.setObjectName("label_22")
        self.expensesSum = QtWidgets.QLineEdit(self.centralwidget)
        self.expensesSum.setEnabled(True)
        self.expensesSum.setGeometry(QtCore.QRect(500, 180, 113, 22))
        self.expensesSum.setMouseTracking(True)
        self.expensesSum.setText("")
        self.expensesSum.setReadOnly(True)
        self.expensesSum.setObjectName("expensesSum")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.label_11.setObjectName("label_11")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(390, 10, 121, 16))
        self.label_23.setObjectName("label_23")
        self.result = QtWidgets.QTableWidget(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(390, 30, 311, 131))
        self.result.setRowCount(3)
        self.result.setColumnCount(5)
        self.result.setObjectName("result")
        item = QtWidgets.QTableWidgetItem()
        self.result.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.result.setHorizontalHeaderItem(4, item)
        self.result.horizontalHeader().setDefaultSectionSize(55)
        App.setCentralWidget(self.centralwidget)

        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "MainWindow"))
        self.label_3.setText(_translate("App", "X"))
        self.label_5.setText(_translate("App", "Z"))
        self.label_7.setText(_translate("App", "3"))
        self.label_6.setText(_translate("App", "2"))
        self.label_4.setText(_translate("App", "Y"))
        self.label_9.setText(_translate("App", "5"))
        self.label_2.setText(_translate("App", "1"))
        self.label_8.setText(_translate("App", "4"))
        self.label.setText(_translate("App", "Предприятия"))
        self.label_10.setText(_translate("App", "Изделия"))
        self.label_12.setText(_translate("App", "Необходимое количество изделий"))
        self.label_14.setText(_translate("App", "Y"))
        self.label_15.setText(_translate("App", "Z"))
        self.label_13.setText(_translate("App", "X"))
        self.label_16.setText(_translate("App", "Максимальная производительность предприятий"))
        self.label_18.setText(_translate("App", "2"))
        self.label_17.setText(_translate("App", "1"))
        self.label_19.setText(_translate("App", "3"))
        self.label_20.setText(_translate("App", "4"))
        self.label_21.setText(_translate("App", "5"))
        self.calcBtn.setText(_translate("App", "Расчитать"))
        self.fromExcel.setText(_translate("App", "Копировать из Excel"))
        self.inExcel.setText(_translate("App", "Сохранить в Excel"))
        self.label_22.setText(_translate("App", "Общие затраты"))
        self.label_11.setText(_translate("App", "Расходы на изделие"))
        self.label_23.setText(_translate("App", "Количество изделий"))
        item = self.result.verticalHeaderItem(0)
        item.setText(_translate("App", "X"))
        item = self.result.verticalHeaderItem(1)
        item.setText(_translate("App", "Y"))
        item = self.result.verticalHeaderItem(2)
        item.setText(_translate("App", "Z"))
        item = self.result.horizontalHeaderItem(0)
        item.setText(_translate("App", "1"))
        item = self.result.horizontalHeaderItem(1)
        item.setText(_translate("App", "2"))
        item = self.result.horizontalHeaderItem(2)
        item.setText(_translate("App", "3"))
        item = self.result.horizontalHeaderItem(3)
        item.setText(_translate("App", "4"))
        item = self.result.horizontalHeaderItem(4)
        item.setText(_translate("App", "5"))
